### ISSUE TITLE
Unable to build with GCC 6.3 on Debian 9

### ISSUE THREAD

**Issue by dopaminereceptionist** [bpeel/notbit#14]
Do I need an earlier gcc version to build this? Thank you!

```notbit# make
make  all-recursive
make[1]: Entering directory '/usr/local/src/notbit'
Making all in doc
make[2]: Entering directory '/usr/local/src/notbit/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/local/src/notbit/doc'
Making all in src
make[2]: Entering directory '/usr/local/src/notbit/src'
  CC       ntb-base58.o
ntb-base58.c: In function ‘ntb_base58_encode’:
ntb-base58.c:53:16: error: storage size of ‘val’ isn’t known
         BIGNUM val;
                ^~~
ntb-base58.c:57:9: warning: implicit declaration of function ‘BN_init’ [-Wimplicit-function-declaration]
         BN_init(&val);
         ^~~~~~~
ntb-base58.c:53:16: warning: unused variable ‘val’ [-Wunused-variable]
         BIGNUM val;
                ^~~
ntb-base58.c: In function ‘ntb_base58_decode’:
ntb-base58.c:105:16: error: storage size of ‘val’ isn’t known
         BIGNUM val;
                ^~~
ntb-base58.c:105:16: warning: unused variable ‘val’ [-Wunused-variable]
Makefile:563: recipe for target 'ntb-base58.o' failed
make[2]: *** [ntb-base58.o] Error 1
make[2]: Leaving directory '/usr/local/src/notbit/src'
Makefile:378: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/notbit'
Makefile:319: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by bpeel** [comment]
This should now be [fixed](https://github.com/bpeel/notbit/commit/a995aeab088ad3083e9b57a6a8251519c65f2f6a) in master.
